[package]
name = "rust-pr"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.92", features = ["backtrace"] }
clap = { version = "4.5.20", features = ["derive"] }
os_display = "0.1.3"
serde_json = "1.0.132"
tracing = "0.1.40"

[[bin]]
name = 'a'
path = 'exp/x.rs'

